# Configuration for license checking
# This file defines which licenses are allowed/prohibited for AGPLv3 compatibility

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - unlicense
  - cc0-1.0
  - 0bsd
  - wtfpl
  - agpl-3.0
  - gpl-3.0
  - lgpl-3.0

# These licenses are incompatible with AGPLv3
banned:
  - gpl-2.0
  - lgpl-2.0
  - lgpl-2.1
  - apache-1.0
  - apache-1.1
  - bsd-4-clause
  - cddl-1.0
  - cpl-1.0
  - epl-1.0
  - ms-pl
  - osl-3.0

# Ignore our own package
ignored:
  npm:
    - yano